language: php

php:
 - 5.5
 - 5.6
 - 7.0
 - hhvm 
script: phpunit

env:
  - DB=mysql
  - SH=bash
  - PACKAGE_VERSION="1.0.*"
  
matrix:
 allow_failures:
   - php: 5.6
   - php: hhvm
 fast_finish: true

services:
 - mysql
