language: php

php:
 - 5.5
 - 5.6
 - 7.0
 - hhvm
 
before_script:
 - composer self-update
install:
 - composer install
 - cp app/config/parameters.yml.dist app/config/parameters.yml
 - php bin/console doctrine:database:create --env=test
 - php bin/console doctrine:schema:create --env=test
 - php bin/console doctrine:fixtures:load -n --env=test

script: phpunit

matrix:
 allow_failures:
   - php: 5.6
   - php: hhvm
 fast_finish: true

services:
 - mysql
